# Generated by Django 4.2.3 on 2024-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_world', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'world',
                'managed': False,
            },
        ),
    ]
