# Generated by Django 4.2.3 on 2024-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worlds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'world',
                'managed': False,
            },
        ),
    ]
