# Generated by Django 4.2.3 on 2024-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worlds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worlds',
            options={},
        ),
    ]
