# Generated by Django 4.2.3 on 2024-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_worlds_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelTable(
            name='worlds',
            table=None,
        ),
    ]
