# Generated by Django 4.2.3 on 2024-05-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dice_alter_worlds_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='World',
        ),
    ]
