# Generated by Django 4.2.3 on 2024-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Головна',
                'verbose_name_plural': 'Головні',
            },
        ),
        migrations.AlterModelOptions(
            name='worlds',
            options={'verbose_name': 'Світ', 'verbose_name_plural': 'Світи'},
        ),
    ]
