# Generated by Django 4.2.3 on 2024-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_alter_worlds_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Механіка',
                'verbose_name_plural': 'Механіки',
            },
        ),
    ]
