# Generated by Django 4.2.3 on 2024-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('type', models.IntegerField()),
                ('type_class', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='weapon/')),
            ],
            options={
                'verbose_name': 'Зброя',
                'verbose_name_plural': 'Зброї',
            },
        ),
    ]
