# Generated by Django 4.2.3 on 2024-05-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='type_class',
            new_name='typeclass',
        ),
    ]
