# Generated by Django 4.2.3 on 2024-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_type_class_weapon_typeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='weapon/')),
            ],
            options={
                'verbose_name': '<Броня>',
                'verbose_name_plural': 'Броні',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='weapon/')),
            ],
            options={
                'verbose_name': 'Спорядження',
                'verbose_name_plural': 'Спорядження',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='weapon/')),
            ],
            options={
                'verbose_name': 'Інструмент',
                'verbose_name_plural': 'Інструменти',
            },
        ),
    ]
