# Generated by Django 4.2.3 on 2024-05-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_armor_equipment_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
