# Generated by Django 4.2.3 on 2024-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='charakteristic',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
