# Generated by Django 4.2.3 on 2024-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characters_charakteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='charakteristic',
            field=models.IntegerField(),
        ),
    ]
